@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Nov 19 15:34:41 +0200 2020
REM SW Build 2960000 on Wed Aug  5 22:57:20 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto fa4620249d184c599ee2f837010916cb --incr --debug typical --relax --mt 2 -L common_pkg_lib -L common_components_lib -L casper_adder_lib -L casper_multiplier_lib -L casper_counter_lib -L casper_fifo_lib -L casper_ram_lib -L casper_requantize_lib -L casper_multiplexer_lib -L dp_pkg_lib -L wb_fft_lib -L r2sdf_fft_lib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot fft_wide_unit_behav wb_fft_lib.fft_wide_unit wb_fft_lib.glbl -log elaborate.log"
call xelab  -wto fa4620249d184c599ee2f837010916cb --incr --debug typical --relax --mt 2 -L common_pkg_lib -L common_components_lib -L casper_adder_lib -L casper_multiplier_lib -L casper_counter_lib -L casper_fifo_lib -L casper_ram_lib -L casper_requantize_lib -L casper_multiplexer_lib -L dp_pkg_lib -L wb_fft_lib -L r2sdf_fft_lib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot fft_wide_unit_behav wb_fft_lib.fft_wide_unit wb_fft_lib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
