#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Aug 07 11:50:45 SAST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 8f3443920199435eaca42eb69f4c3ed1 --incr --debug typical --relax --mt 8 -L common_components_lib -L common_pkg_lib -L casper_multiplier_lib -L casper_counter_lib -L casper_ram_lib -L casper_requantize_lib -L r2sdf_fft_lib -L secureip --snapshot tb_rTwoSDF_behav r2sdf_fft_lib.tb_rTwoSDF -log elaborate.log"
xelab -wto 8f3443920199435eaca42eb69f4c3ed1 --incr --debug typical --relax --mt 8 -L common_components_lib -L common_pkg_lib -L casper_multiplier_lib -L casper_counter_lib -L casper_ram_lib -L casper_requantize_lib -L r2sdf_fft_lib -L secureip --snapshot tb_rTwoSDF_behav r2sdf_fft_lib.tb_rTwoSDF -log elaborate.log

