# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx690tffg1927-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/casper_wb_fft/casper_wb_fft.cache/wt [current_project]
set_property parent.project_path /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/casper_wb_fft/casper_wb_fft.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/casper_wb_fft/casper_wb_fft.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library common_pkg_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_pkg/common_pkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_pkg/common_str_pkg.vhd
}
read_vhdl -library common_components_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_pipeline.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_async.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_areset.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_bit_delay.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_pipeline_sl.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_delay.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_switch.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_spulse.vhd
}
read_vhdl -library casper_adder_lib /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_adder/casper_common_add_sub.vhd
read_vhdl -library casper_multiplier_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplier/tech_mult_component.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplier/tech_complex_mult.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplier/common_complex_mult.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplier/ip_cmult_rtl_3dsp.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplier/ip_cmult_rtl_4dsp.vhd
}
read_vhdl -library casper_counter_lib /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_counter/common_counter.vhd
read_vhdl -library casper_mm_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_mm/common_field_pkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_mm/common_mem_mux.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_mm/common_reg_cross_domain.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_mm/common_reg_r_w.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_mm/common_reg_r_w_dc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_mm/mm_fields.vhd
}
read_vhdl -library casper_fifo_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/common_rl_decrease.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/common_fifo_rd.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/tech_fifo_component_pkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/tech_fifo_sc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/common_fifo_sc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/ip_stratixiv_fifo_sc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/ip_xilinx_fifo_sc.vhd
}
read_vhdl -library casper_ram_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_ram_pkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/tech_memory_component_pkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/tech_memory_ram_crw_crw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/tech_memory_ram_cr_cw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_ram_crw_crw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_paged_ram_crw_crw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_paged_ram_rw_rw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_paged_ram_r_w.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/tech_memory_ram_crwk_crw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_ram_crw_crw_ratio.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_ram_rw_rw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_ram_r_w.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/ip_xpm_ram_cr_cw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/ip_xpm_ram_crw_crw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/ip_xpm_ram_crwk_crw.vhd
}
read_vhdl -library casper_requantize_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_requantize/common_round.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_requantize/common_resize.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_requantize/common_requantize.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_requantize/dp_requantize.vhd
}
read_vhdl -library casper_multiplexer_lib /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplexer/common_zip.vhd
read_vhdl -library dp_components_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_dp_components/dp_hold_ctrl.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_dp_components/dp_hold_input.vhd
}
read_vhdl -library dp_pkg_lib /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_dp_pkg/dp_stream_pkg.vhd
read_vhdl -library casper_pipeline_lib /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_pipeline/dp_pipeline.vhd
read_vhdl -library wb_fft_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/fft_pkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/fft_r2_bf_par.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/fft_r2_par.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/fft_sepa.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/fft_reorder_sepa_pipe.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/fft_r2_pipe.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/fft_sepa_wide.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/fft_r2_wide.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/fft_wide_unit_control.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_wb_fft/fft_wide_unit.vhd
}
read_vhdl -library r2sdf_fft_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/twiddlesPkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoSDFPkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoBF.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoWMul.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoBFStage.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoWeights.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoSDFStage.vhd
}
read_vhdl -library casper_statistics_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_statistics/st_ctrl.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_statistics/st_acc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_statistics/st_calc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_statistics/st_sst.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fft_wide_unit -part xc7vx690tffg1927-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fft_wide_unit.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fft_wide_unit_utilization_synth.rpt -pb fft_wide_unit_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
