
function common_counter_config(this_block)

  % Revision History:
  %
  %   21-May-2020  (11:11 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_counter/common_counter.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('common_counter');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('clk');
  this_block.addSimulinkInport('clken');
  this_block.addSimulinkInport('cnt_clr');
  this_block.addSimulinkInport('cnt_ld');
  this_block.addSimulinkInport('cnt_en');
  this_block.addSimulinkInport('cnt_max');
  this_block.addSimulinkInport('load');

  this_block.addSimulinkOutport('count');


  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1)
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('clk').width ~= 1)
      this_block.setError('Input data type for port "clk" must have width=1.');
    end

    this_block.port('clk').useHDLVector(false);

    if (this_block.port('clken').width ~= 1)
      this_block.setError('Input data type for port "clken" must have width=1.');
    end

    this_block.port('clken').useHDLVector(false);

    if (this_block.port('cnt_clr').width ~= 1)
      this_block.setError('Input data type for port "cnt_clr" must have width=1.');
    end

    this_block.port('cnt_clr').useHDLVector(false);

    if (this_block.port('cnt_ld').width ~= 1)
      this_block.setError('Input data type for port "cnt_ld" must have width=1.');
    end

    this_block.port('cnt_ld').useHDLVector(false);

    if (this_block.port('cnt_en').width ~= 1)
      this_block.setError('Input data type for port "cnt_en" must have width=1.');
    end

    this_block.port('cnt_en').useHDLVector(false);

    % (!) Port 'cnt_max' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    % (!) Port 'load' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

  % (!) Port 'count' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

  uniqueInputRates = unique(this_block.getInputRates);
  CommonCounter = this_block.blockName; %This is the name of the black box block
  ccntr_mask = get_param(CommonCounter,'Parent'); %This is the name of the black box subsystem
  latency = (get_param(ccntr_mask,'g_latency')); %Grab the 'direction' parameter from the parent's mask
  initval = (get_param(ccntr_mask,'g_init'));
  width = (get_param(ccntr_mask,'g_width'));
  maxval = (get_param(ccntr_mask,'g_max'));
  step_size = (get_param(ccntr_mask,'g_step_size'));

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('g_latency','NATURAL',latency);
  this_block.addGeneric('g_init','INTEGER',initval);
  this_block.addGeneric('g_width','NATURAL',width);
  this_block.addGeneric('g_max','NATURAL',maxval);
  this_block.addGeneric('g_step_size','INTEGER',step_size);

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('common_counter.vhd');

return;


