#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Aug 11 11:06:29 SAST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6056f71df73a47be873e49aa656d4c01 --incr --debug typical --relax --mt 8 -L common_pkg_lib -L casper_ram_lib -L common_components_lib -L secureip -L xpm --snapshot tb_common_paged_ram_crw_crw_behav casper_ram_lib.tb_common_paged_ram_crw_crw -log elaborate.log"
xelab -wto 6056f71df73a47be873e49aa656d4c01 --incr --debug typical --relax --mt 8 -L common_pkg_lib -L casper_ram_lib -L common_components_lib -L secureip -L xpm --snapshot tb_common_paged_ram_crw_crw_behav casper_ram_lib.tb_common_paged_ram_crw_crw -log elaborate.log

