
function casper_common_add_sub_config(this_block)

  % Revision History:
  %
  %   20-May-2020  (12:51 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_adder/casper_common_add_sub.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('common_add_sub');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('clk');
  this_block.addSimulinkInport('clken');
  this_block.addSimulinkInport('sel_add');
  this_block.addSimulinkInport('in_a');
  this_block.addSimulinkInport('in_b');

  this_block.addSimulinkOutport('result');


  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('clk').width ~= 1)
      this_block.setError('Input data type for port "clk" must have width=1.');
    end

    this_block.port('clk').useHDLVector(false);

    if (this_block.port('clken').width ~= 1)
      this_block.setError('Input data type for port "clken" must have width=1.');
    end

    this_block.port('clken').useHDLVector(false);

    if (this_block.port('sel_add').width ~= 1)
      this_block.setError('Input data type for port "sel_add" must have width=1.');
    end

    this_block.port('sel_add').useHDLVector(false);

    % (!) Port 'in_a' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    % (!) Port 'in_b' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

  % (!) Port 'result' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);
    
      % Grab HDL parameters from simulink mask
  myname = this_block.blockName; %This is the name of the black box block
  bb_mask = get_param(myname,'Parent'); %This is the name of the black box subsystem
  direction = (get_param(bb_mask,'g_direction')); %Grab the 'direction' parameter from the parent's mask
  representation = (get_param(bb_mask,'g_representation'));
  pipeline_inp = (get_param(bb_mask,'g_pipeline_input'));
  pipeline_out = (get_param(bb_mask,'g_pipeline_output'));
  in_dat_w = (get_param(bb_mask,'g_in_dat_w'));
  out_dat_w = (get_param(bb_mask,'g_out_dat_w'));

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('g_direction','STRING',direction);
  this_block.addGeneric('g_representation','STRING',representation);
  this_block.addGeneric('g_pipeline_input','NATURAL',pipeline_inp);
  this_block.addGeneric('g_pipeline_output','NATURAL',pipeline_out);
  this_block.addGeneric('g_in_dat_w','NATURAL',in_dat_w);
  this_block.addGeneric('g_out_dat_w','NATURAL',out_dat_w);

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('casper_common_add_sub.vhd');
  
return;


