
function top_fil_config(this_block)

  % Revision History:
  %
  %   16-Mar-2021  (08:49 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /data/home/talonm/casper_dspdevel/wrappers/simulink/filter_blk_fil_top.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('top_fil');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('in_val');
  this_block.addSimulinkInport('in_dat_arr_0');

  this_block.addSimulinkOutport('out_val');
  this_block.addSimulinkOutport('out_dat_arr_0');

  out_val_port = this_block.port('out_val');
  out_val_port.setType('UFix_1_0');
  out_val_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('in_val').width ~= 1);
      this_block.setError('Input data type for port "in_val" must have width=1.');
    end

    this_block.port('in_val').useHDLVector(false);

    % (!) Port 'in_dat_arr_0' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

  % (!) Port 'out_dat_arr_0' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('g_big_endian_wb_in','boolean','false');
  this_block.addGeneric('g_big_endian_wb_out','boolean','false');
  this_block.addGeneric('g_fil_ppf','t_fil_ppf','c_fil_ppf');
  this_block.addGeneric('g_fil_ppf_pipeline','t_fil_ppf_pipeline','c_fil_ppf_pipeline');
  this_block.addGeneric('g_coefs_file','string','c_coefs_file');
  this_block.addGeneric('g_technology','natural','0');
  this_block.addGeneric('g_ram_primitive','string','"auto"');

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('filter_blk_fil_top.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

