set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:1 order:LATE scoped_inst:{fft_wide_unit/u_fft_wide/gen_fft_r2_wide.gen_separate.u_separator/gen_dual_paged_rams[0].u_buff/u_rw_rw/u_crw_crw/gen_adr.u_mem/gen_simple_dual_port.u_ram/gen_ip_xilinx.u1/xpm_memory_sdpram_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:2 order:LATE scoped_inst:{fft_wide_unit/u_fft_wide/gen_fft_r2_wide.gen_separate.u_separator/gen_dual_paged_rams[1].u_buff/u_rw_rw/u_crw_crw/gen_adr.u_mem/gen_simple_dual_port.u_ram/gen_ip_xilinx.u1/xpm_memory_sdpram_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:3 order:LATE scoped_inst:{fft_wide_unit/u_fft_wide/gen_fft_r2_wide.gen_separate.u_separator/gen_dual_paged_rams[2].u_buff/u_rw_rw/u_crw_crw/gen_adr.u_mem/gen_simple_dual_port.u_ram/gen_ip_xilinx.u1/xpm_memory_sdpram_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:4 order:LATE scoped_inst:{fft_wide_unit/u_fft_wide/gen_fft_r2_wide.gen_separate.u_separator/gen_dual_paged_rams[3].u_buff/u_rw_rw/u_crw_crw/gen_adr.u_mem/gen_simple_dual_port.u_ram/gen_ip_xilinx.u1/xpm_memory_sdpram_inst} unmanaged:yes} [current_design]
current_instance {fft_wide_unit/u_fft_wide/gen_fft_r2_wide.gen_separate.u_separator/gen_dual_paged_rams[0].u_buff/u_rw_rw/u_crw_crw/gen_adr.u_mem/gen_simple_dual_port.u_ram/gen_ip_xilinx.u1/xpm_memory_sdpram_inst}
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {fft_wide_unit/u_fft_wide/gen_fft_r2_wide.gen_separate.u_separator/gen_dual_paged_rams[1].u_buff/u_rw_rw/u_crw_crw/gen_adr.u_mem/gen_simple_dual_port.u_ram/gen_ip_xilinx.u1/xpm_memory_sdpram_inst}
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {fft_wide_unit/u_fft_wide/gen_fft_r2_wide.gen_separate.u_separator/gen_dual_paged_rams[2].u_buff/u_rw_rw/u_crw_crw/gen_adr.u_mem/gen_simple_dual_port.u_ram/gen_ip_xilinx.u1/xpm_memory_sdpram_inst}
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {fft_wide_unit/u_fft_wide/gen_fft_r2_wide.gen_separate.u_separator/gen_dual_paged_rams[3].u_buff/u_rw_rw/u_crw_crw/gen_adr.u_mem/gen_simple_dual_port.u_ram/gen_ip_xilinx.u1/xpm_memory_sdpram_inst}
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
