# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx690tffg1927-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/r2SDF_FFT_proj/r2SDF_FFT_proj.cache/wt [current_project]
set_property parent.project_path /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/r2SDF_FFT_proj/r2SDF_FFT_proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/r2SDF_FFT_proj/r2SDF_FFT_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library common_components_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_bit_delay.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_pipeline.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_pipeline_sl.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_delay.vhd
}
read_vhdl -library common_pkg_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_pkg/common_pkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/common_pkg/common_str_pkg.vhd
}
read_vhdl -library casper_multiplier_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplier/tech_mult_component.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplier/tech_complex_mult.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplier/common_complex_mult.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplier/ip_cmult_rtl_3dsp.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_multiplier/ip_cmult_rtl_4dsp.vhd
}
read_vhdl -library casper_counter_lib /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_counter/common_counter.vhd
read_vhdl -library casper_ram_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_ram_pkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/tech_memory_component_pkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/tech_memory_ram_crw_crw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/tech_memory_ram_cr_cw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_ram_crw_crw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_paged_ram_crw_crw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_paged_ram_rw_rw.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/common_paged_ram_r_w.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_ram/ip_xilinx_ram_cr_cw.vhd
}
read_vhdl -library casper_requantize_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_requantize/common_round.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_requantize/common_resize.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_requantize/common_requantize.vhd
}
read_vhdl -library r2sdf_fft_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoBF.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoBFStage.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoOrder.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/twiddlesPkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoSDFPkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoWeights.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoWMul.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoSDFStage.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/r2sdf_fft/rTwoSDF.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top rTwoSDF -part xc7vx690tffg1927-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rTwoSDF.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rTwoSDF_utilization_synth.rpt -pb rTwoSDF_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
