# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7vx690tffg1927-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/casper_fifo_proj/casper_fifo_proj.cache/wt [current_project]
set_property parent.project_path /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/casper_fifo_proj/casper_fifo_proj.xpr [current_project]
set_property XPM_LIBRARIES XPM_FIFO [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/casper_fifo_proj/casper_fifo_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library common_pkg_lib /home/talon/Documents/CASPERWORK/casper_dspdevel/common_pkg/common_pkg.vhd
read_vhdl -library common_components_lib /home/talon/Documents/CASPERWORK/casper_dspdevel/common_components/common_areset.vhd
read_vhdl -library casper_fifo_lib {
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/tech_fifo_component_pkg.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/tech_fifo_dc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/common_fifo_dc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/tech_fifo_sc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/common_fifo_sc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/dp_fifo_core.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/dp_fifo_dc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/dp_fifo_sc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/dp_fifo_fill_core.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/dp_fifo_fill_sc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/ip_stratixiv_fifo_dc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/ip_stratixiv_fifo_sc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/ip_xilinx_fifo_dc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/ip_xilinx_fifo_sc.vhd
  /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_fifo/dp_fifo_fill.vhd
}
read_vhdl -library dp_pkg_lib /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_dp_pkg/dp_stream_pkg.vhd
read_vhdl -library dp_components_lib /home/talon/Documents/CASPERWORK/casper_dspdevel/casper_dp_components/dp_latency_adapter.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top dp_fifo_fill -part xc7vx690tffg1927-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dp_fifo_fill.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dp_fifo_fill_utilization_synth.rpt -pb dp_fifo_fill_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
